name: artif.yml

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  download-artifacts:
    runs-on: windows-latest # Match the OS used in the upload workflow

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: Run artif.py Workflow # The name of the upload workflow
        name: daily-videos
        path: C:\Users\captk\youtube-ai-agent\build\artifacts
