name: Run Main Script Daily

on:
  schedule:
    # Run daily at 07:00 UTC-5 (12:00 UTC)
    - cron: '0 7 * * *'

  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      reason:
        description: 'Reason for manual execution'
        required: false

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Specify the Python version used for your script

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Main Script
      env:
        YT_API_KEY: ${{ secrets.YT_API_KEY }} # Store your API key in GitHub Secrets
      run: python main.py
