name: Daily Vlog Automation

on:
  
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  daily-vlog:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Setup Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    # Step 4: Install dependencies
    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    # Step 5: Run the main automation script
    - name: Run main.py
      run: python main.py
