name: YouTube Automation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Purge Python Cache
        run: |
          sudo rm -rf /opt/hostedtoolcache/Python/*
          sudo apt-get install -y curl  # Required for image downloads

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        env:
          YT_EMAIL: ${{ secrets.YT_EMAIL }}
          YT_PASSWORD: ${{ secrets.YT_PASSWORD }}
        run: |
          mkdir -p audio videos images
          python main.py
