name: Run main.py Workflow

on:
  schedule:
    - cron: '0 12 * * *' # Runs daily at 12:00 PM UTC (7:00 AM CST/CDT)
  workflow_dispatch: # Allows manual triggering
  push: # Triggers when code is pushed to the repository
    branches:
      - main

jobs:
  run-script:
    runs-on: windows-latest # Updated to match your environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10 # Use a stable version of Python

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Run main.py to generate videos
      run: |
        python main.py

    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: Run artif.py Workflow # The name of the upload workflow
        name: daily-videos
        path: C:\Users\captk\youtube-ai-agent\build\artifacts
