name: Run main.py Workflow

on:
  schedule:
    - cron: '00 12 * * *' # Runs at 7:00 AM CST or 7:00 AM CDT adjusted to UTC time
  workflow_dispatch: # Allows manual triggering of the workflow
  push: # Triggers when code is pushed to the repository
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13 # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Create required directories
      run: |
        mkdir -p audio
        mkdir -p video

    - name: Run main.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS: .gitignore/client_secrets2.json
      run: |
        python main.py

    - name: Generate artifacts
      run: |
        mkdir -p artifacts
        python main.py # Replace with the script that generates artifacts
        # Move or copy generated files to the artifacts folder
        mv generated_file_1.txt artifacts/
        mv generated_file_2.log artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: daily-artifacts
        path: -r "c:\Users\captk\videos
