name: Daily AI Agent on.



schedule:

- cron: "0

0

** *"

# Runs

daily at midnight UTC

jobs:

run-bot:

runs-on: ubuntu-latest steps:

﻿﻿name: Checkout code
uses: actions/checkout@v4
﻿﻿name: Install Python uses: actions/ setup-
python@v4 with:
python-version: '3.10'
﻿﻿name: Install dependencies run: pip install -r
requirements.txt

- name: Run Script env:

HF_TOKEN: $

{{ secrets. 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  33 run: python main.py
