name: Video Pipeline

on:
  workflow_dispatch:

jobs:
  example-job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a script
        run: echo "Running on a self-hosted runner"
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.13"

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Dependencies
        run: pip install requests

      - name: Run Video Pipeline
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: python main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
         name: my-artifact
         path: |
            video_clips/
            output_video.mp4
